---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        role: user-api
    spec:
      containers:
      - name: user-api
        image: slowe/flask-web-svc:latest
        ports:
        - containerPort: 6000
        env:
        - name: PORT
          value: "6000"
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: http_proxy
          value: $(NODE_NAME):4140
---
apiVersion: v1
kind: Service
metadata:
  name: user-api
  labels:
    role: user-api-svc
spec:
  ports:
  - port: 6000
    targetPort: 6000
  selector:
    role: user-api
---
