---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 3
  template:
    metadata:
      labels:
        role: order-api
    spec:
      containers:
      - name: order-api
        image: slowe/flask-web-svc:latest
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  labels:
    role: order-api-svc
spec:
  ports:
  - port: 7000
    targetPort: 7000
  selector:
    role: order-api
---
